name: Build & Run Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run:  mvn clean package -DskipTests

      - name: List JAR files
        run: ls -la target/

      - name: Run Spring Boot app (with log capture)
        run: |
          java -jar target/*.jar || true
          
      - name: Build Docker image
        run: docker build -t spring-boot-app .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 spring-boot-app
